# Generated by Django 5.0.3 on 2024-04-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('credit_card', models.CharField(max_length=16)),
                ('expire_date', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
            ],
        ),
    ]
